// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package model

import "database/sql"

func ScanBoard(r *sql.Row) (Board, error) {
	var s Board
	if err := r.Scan(
		&s.ID,
		&s.User_Id,
		&s.Date,
		&s.Created,
		&s.Updated,
	); err != nil {
		return Board{}, err
	}
	return s, nil
}

func ScanBoards(rs *sql.Rows) ([]Board, error) {
	structs := make([]Board, 0, 16)
	var err error
	for rs.Next() {
		var s Board
		if err = rs.Scan(
			&s.ID,
			&s.User_Id,
			&s.Date,
			&s.Created,
			&s.Updated,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanUser(r *sql.Row) (User, error) {
	var s User
	if err := r.Scan(
		&s.ID,
		&s.Name,
		&s.Email,
		&s.Salt,
		&s.Salted,
		&s.Created,
		&s.Updated,
	); err != nil {
		return User{}, err
	}
	return s, nil
}

func ScanUsers(rs *sql.Rows) ([]User, error) {
	structs := make([]User, 0, 16)
	var err error
	for rs.Next() {
		var s User
		if err = rs.Scan(
			&s.ID,
			&s.Name,
			&s.Email,
			&s.Salt,
			&s.Salted,
			&s.Created,
			&s.Updated,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanTodo(r *sql.Row) (Todo, error) {
	var s Todo
	if err := r.Scan(
		&s.ID,
		&s.Board_Id,
		&s.User_Id,
		&s.Title,
		&s.Completed,
		&s.Pos_Top,
		&s.Pos_Left,
		&s.Width,
		&s.Height,
		&s.Created,
		&s.Updated,
	); err != nil {
		return Todo{}, err
	}
	return s, nil
}

func ScanTodos(rs *sql.Rows) ([]Todo, error) {
	structs := make([]Todo, 0, 16)
	var err error
	for rs.Next() {
		var s Todo
		if err = rs.Scan(
			&s.ID,
			&s.Board_Id,
			&s.User_Id,
			&s.Title,
			&s.Completed,
			&s.Pos_Top,
			&s.Pos_Left,
			&s.Width,
			&s.Height,
			&s.Created,
			&s.Updated,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

