development:
  dialect: mysql
  datasource: root:password@tcp(localhost:3306)/supertodo?parseTime=true&collation=utf8_general_ci&interpolateParams=true
  dir: migrations

test:
  dialect: mysql
  datasource: root:password@tcp(localhost:3306)/test-supertodo?parseTime=true&collation=utf8_general_ci&interpolateParams=true
